[tool.poetry]
name = "game-pulse"
version = "0.1.0"
description = "Game Pulse - Game aggregator website"
authors = ["Akwaboah Christopher <christakwaajr@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
Flask = "3.0.0"
Flask-SQLAlchemy = "3.0.5"
SQLAlchemy = "2.1.0b3"
Werkzeug = "3.0.1"
gunicorn = "21.2.0"
python-dotenv = "1.0.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
